### ISSUE TITLE
typo on website

### ISSUE THREAD

**Issue by edwintorok** [sapientml/sapientml#42]
**Describe the bug**
https://sapientml.io

"High speed: It can generate an AI model quickly by evaluating not all the combinations of the machine learnig pipelines but only the most plausible machine learning pipelines."

**To Reproduce**
Visit https://sapientml.io

**Expected behavior**
"learning" instead of "learnig".

**Additional context**
I suggest running a spell checker on the entire website.

**Comment by kimusaku** [comment]
@edwintorok thank you very much for mentioning the typo on website. We have run the supell checker on the website and fixed it. I will close the issue if you do not mind. Thanks again!
