### ISSUE TITLE
Added LabelEncoder for multiple target columns #354 (Migrated Issue)

### ISSUE THREAD

**Issue by tahalpara** [sapientml/sapientml#60]
**This issue is a migrated issue from the old repo https://github.com/F-AutoML/sapientml/issues/354
Details as follows**

[SoHasegawa](https://github.com/SoHasegawa)(so.hasegawa) commented [on Oct 3, 2022](https://github.com/F-AutoML/sapientml/issues/354#issue-1394285005)
This issue is related to https://github.com/F-AutoML/sapientml/issues/224 and https://github.com/F-AutoML/sapientml/pull/350.

To tackle https://github.com/F-AutoML/sapientml/issues/224, when a XGBClassifier is chosen as a model, I added LabelEncoder to the MODEL block in https://github.com/F-AutoML/sapientml/pull/350. However, this modification does not solve the case where the number of target columns are multiple because LabelEncoder can be applied to only single column. To solve the problem, I propose that LabelEncoder is applied to each target column using for loop or other implementations.

[AkiraUra](https://github.com/AkiraUra)(Akira Ura) commented [on Dec 1, 2022](https://github.com/F-AutoML/sapientml/issues/354#issuecomment-1333508528)
The template related to this issue is the below:
[sapientml/sapientml/core/adaptation/generation/templates_library/model_templates/model.py.jinja](https://github.com/F-AutoML/sapientml/blob/5a95d8ad0325628f678234f5404d05ce7f9aa148/sapientml/core/adaptation/generation/templates_library/model_templates/model.py.jinja#L25-L36)

So, the generated code is like the below:

```
from sklearn.preprocessing import LabelEncoder 
  
_le = LabelEncoder() 
__target_train = _le.fit_transform(__target_train) 

__model.fit(__feature_train, __target_train) 
__y_pred = __model.predict(__feature_test) 

__y_pred = _le.inverse_transform(__y_pred) 
```

If __target_train has one dimension such as __target_train = pd.DataFrame(['a', 'a', 'b', 'b', 'a', 'a']), the code works without any errors, but if __target_train has more than one dimension such as __target_train = pd.DataFrame([['a', 'a', 'b', 'b', 'a', 'a'], ['x', 'x', 'x', 'y', 'y', 'y']]), the code fails in _le.fit_transform(__target_train). This is the issue.

@[AkiraUra](https://github.com/AkiraUra) AkiraUra moved this from 🆕 New to 🔖 Ready in [SapientML Development backlog](https://github.com/orgs/F-AutoML/projects/2) [on Feb 1](https://github.com/F-AutoML/sapientml/issues/354#event-5bdb069e-a183-5fe7-bea7-923c456e8e78)
@[kimusaku](https://github.com/kimusaku) kimusaku linked a pull request [on Feb 28 ](https://github.com/F-AutoML/sapientml/issues/354#ref-pullrequest-1599548554)that will close this issue
https://github.com/F-AutoML/sapientml/pull/665
 Open
@[AkiraUra](https://github.com/AkiraUra) AkiraUra mentioned this issue [on Apr 19](https://github.com/F-AutoML/sapientml/issues/354#ref-issue-1614697153)
https://github.com/F-AutoML/sapientml/issues/687
Open
@[KawaiRie1024](https://github.com/KawaiRie1024) KawaiRie1024 mentioned this issue [on Jun 1](https://github.com/F-AutoML/sapientml/issues/354#ref-issue-1735459349)
https://github.com/F-AutoML/sapientml/issues/831
Closed
@[mariko-sugawara](https://github.com/mariko-sugawara) mariko-sugawara mentioned this issue [on Jul 27](https://github.com/F-AutoML/sapientml/issues/354#ref-issue-1824107936)
https://github.com/F-AutoML/sapientml/issues/900
Open

**Comment by kimusaku** [comment]
@tahalpara
Thanks for the issue, but it looks this does not fit to the current status. I will once close it, and please create a new one.
