### ISSUE TITLE
exception on regression colab examples 

### ISSUE THREAD

**Issue by tamirgold** [sapientml/sapientml#77]
non touched colab throws this error on this line :
cls.fit(train_data, ignore_columns=["Id"])
RuntimeError: This event loop is already running

**Comment by tamirgold** [comment]
what do you mean by - users' first issue ?

**Comment by kimusaku** [comment]
@tamirgold
Thank you very much for reporting the issue.
We will investigate and fix it soon.
Regarding the message from github-actions, I found we did not complete to configure the action.
I fixed it and apologies for confusing you.
